-- MySQL Script generated by MySQL Workbench
-- Mon Feb  6 22:47:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TaxiService
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TaxiService
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TaxiService` DEFAULT CHARACTER SET utf8 ;
USE `TaxiService` ;

-- -----------------------------------------------------
-- Table `TaxiService`.`TaxiService`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`TaxiService` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Drivers` VARCHAR(45) NOT NULL,
  `Cars` VARCHAR(45) NULL,
  `Customer` VARCHAR(45) NULL,
  `Meter` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Drivers_UNIQUE` (`Drivers` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`Employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Job` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`Taxi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`Taxi` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Model` VARCHAR(45) NOT NULL,
  `Year` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`Passenger` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`TaxiService_Passenger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`TaxiService_Passenger` (
  `TaxiService_id` INT NOT NULL,
  `Passenger_id` INT NOT NULL,
  PRIMARY KEY (`TaxiService_id`, `Passenger_id`),
  INDEX `fk_TaxiService_has_Passenger_Passenger1_idx` (`Passenger_id` ASC),
  INDEX `fk_TaxiService_has_Passenger_TaxiService_idx` (`TaxiService_id` ASC),
  CONSTRAINT `fk_TaxiService_has_Passenger_TaxiService`
    FOREIGN KEY (`TaxiService_id`)
    REFERENCES `TaxiService`.`TaxiService` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaxiService_has_Passenger_Passenger1`
    FOREIGN KEY (`Passenger_id`)
    REFERENCES `TaxiService`.`Passenger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`TaxiService_Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`TaxiService_Employees` (
  `TaxiService_id` INT NOT NULL,
  `Employees_id` INT NOT NULL,
  PRIMARY KEY (`TaxiService_id`, `Employees_id`),
  INDEX `fk_TaxiService_has_Employees_Employees1_idx` (`Employees_id` ASC),
  INDEX `fk_TaxiService_has_Employees_TaxiService1_idx` (`TaxiService_id` ASC),
  CONSTRAINT `fk_TaxiService_has_Employees_TaxiService1`
    FOREIGN KEY (`TaxiService_id`)
    REFERENCES `TaxiService`.`TaxiService` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaxiService_has_Employees_Employees1`
    FOREIGN KEY (`Employees_id`)
    REFERENCES `TaxiService`.`Employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`TaxiService_Taxi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`TaxiService_Taxi` (
  `TaxiService_id` INT NOT NULL,
  `Taxi_id` INT NOT NULL,
  PRIMARY KEY (`TaxiService_id`, `Taxi_id`),
  INDEX `fk_TaxiService_has_Taxi_Taxi1_idx` (`Taxi_id` ASC),
  INDEX `fk_TaxiService_has_Taxi_TaxiService1_idx` (`TaxiService_id` ASC),
  CONSTRAINT `fk_TaxiService_has_Taxi_TaxiService1`
    FOREIGN KEY (`TaxiService_id`)
    REFERENCES `TaxiService`.`TaxiService` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaxiService_has_Taxi_Taxi1`
    FOREIGN KEY (`Taxi_id`)
    REFERENCES `TaxiService`.`Taxi` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`Destination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`Destination` (
  `id`  NOT NULL,
  `locationName` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`TaxiService_Destination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`TaxiService_Destination` (
  `TaxiService_id` INT NOT NULL AUTO_INCREMENT,
  `Destination_id`  NOT NULL,
  PRIMARY KEY (`TaxiService_id`, `Destination_id`),
  INDEX `fk_TaxiService_has_Destination_Destination1_idx` (`Destination_id` ASC),
  INDEX `fk_TaxiService_has_Destination_TaxiService1_idx` (`TaxiService_id` ASC),
  CONSTRAINT `fk_TaxiService_has_Destination_TaxiService1`
    FOREIGN KEY (`TaxiService_id`)
    REFERENCES `TaxiService`.`TaxiService` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TaxiService_has_Destination_Destination1`
    FOREIGN KEY (`Destination_id`)
    REFERENCES `TaxiService`.`Destination` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`Driver` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `dOB` INT NOT NULL,
  `shift` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Driver_UNIQUE` (`full_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`Employees_Driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`Employees_Driver` (
  `Employees_id` INT NOT NULL,
  `Driver_id` INT NOT NULL,
  PRIMARY KEY (`Employees_id`, `Driver_id`),
  INDEX `fk_Employees_has_Driver_Driver1_idx` (`Driver_id` ASC),
  INDEX `fk_Employees_has_Driver_Employees1_idx` (`Employees_id` ASC),
  CONSTRAINT `fk_Employees_has_Driver_Employees1`
    FOREIGN KEY (`Employees_id`)
    REFERENCES `TaxiService`.`Employees` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employees_has_Driver_Driver1`
    FOREIGN KEY (`Driver_id`)
    REFERENCES `TaxiService`.`Driver` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`fare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`fare` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` INT NULL,
  `tip` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TaxiService`.`Passenger_fare`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TaxiService`.`Passenger_fare` (
  `Passenger_id` INT NOT NULL,
  `fare_id` INT NOT NULL,
  PRIMARY KEY (`Passenger_id`, `fare_id`),
  INDEX `fk_Passenger_has_fare_fare1_idx` (`fare_id` ASC),
  INDEX `fk_Passenger_has_fare_Passenger1_idx` (`Passenger_id` ASC),
  CONSTRAINT `fk_Passenger_has_fare_Passenger1`
    FOREIGN KEY (`Passenger_id`)
    REFERENCES `TaxiService`.`Passenger` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Passenger_has_fare_fare1`
    FOREIGN KEY (`fare_id`)
    REFERENCES `TaxiService`.`fare` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
